language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
before_install:
- openssl aes-256-cbc -K $encrypted_555fd80cc8bb_key -iv $encrypted_555fd80cc8bb_iv
  -in google-services.json.enc -out app/google-services.json -d
