language: android
env:
  global:
    secure: DUz+Kh5BSScPA8kzs5YcKnXSitFWI00TdzMZMiXTL1fA3b3z23XgFu2H0sA9DpiLNVpscAuF2KcYL8GXPthw0eWt5iniHOSNbPD8mkxWYF+dnqeS11ouficBLXQxn43BBP3r6BfVs5BouB7/mLo+efKP8P1bBHV+pXy48RmVH7GQUWaS/xuWlAlDINg+PrBG3+KTP85OBFQ0Pqr7rXPd5znh+DxqIYGD5phCIv/BK5CZe1uMgq3gkI+kd6zFJ+CNGVVuh/ebMuxQLWEyiQGFKHa3PV1Ktc+/gCrmnTtQDPdm9Sc1s0hwkrMKpfYNpZFQ/hUSpK3YsuEIjklCxA+ExyxzSEoofI/v56rwlKeB0jXK6TLbqIMJEZhfra/KS401BkzBD/z9a8fY4V0eqL16MW3i5YVuQLrSVaVKUyuy3Q9ukD4qofcGfA/uDTuI9pHk2t2SS9N+QQlICAyclXssVo7AWYlHMdE5KPqOuW3aXLwey0A11OoAH4U7KgKBJeVb3GN9Vvt3vmrfDO3bZeKuUb/Ihj8FA4f0Tlpitzg7yEyctzSjR15eUsmZd/LYnhnjE/2Dd2HH3M37ATLNQ2WSsZhq7gqX4zf3tdT2y0UK3odXpPw+S1+7t/xUmFm8SjIN1qVPGvtwu7h2T0oG/aE49/6BeyyakAYmCxkPKGEyOyQ=
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - android-27
  - sys-img-armeabi-v7a-android-22
before_install:
- openssl aes-256-cbc -K $encrypted_555fd80cc8bb_key -iv $encrypted_555fd80cc8bb_iv -in secrets.zip.enc -out secrets.zip -d
- unzip secrets.zip
- mv google-services.json app/google-services.json
- mv google_maps_api.xml app/src/main/res/values/google_maps_api.xml
- mv tankerkoenig_key.xml app/src/main/res/values/tankerkoenig_key.xml
install:
- bundle install
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && ([ "$TRAVIS_BRANCH" = "master" ] || [ "$TRAVIS_BRANCH" = "alpha" ] || [ "$TRAVIS_BRANCH" = "beta" ]); then
      ./gradlew assembleRelease;
      jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${TRAVIS_BUILD_DIR}/tankbuch_keystore.jks -storepass $password -keypass $password ${TRAVIS_BUILD_DIR}/app/build/outputs/apk/release/app-release-unsigned.apk tankbuch;
      jarsigner -verify app/build/outputs/apk/release/app-release-unsigned.apk;
      ${ANDROID_HOME}build-tools/28.0.2/zipalign -v 4 ${TRAVIS_BUILD_DIR}/app/build/outputs/apk/release/app-release-unsigned.apk ${TRAVIS_BUILD_DIR}/app/build/outputs/apk/release/app-release-signed.apk;
  else
    ./gradlew build;
  fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    fastlane release;
  fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "alpha" ]; then
    fastlane alpha;
  fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "beta" ]; then
    fastlane beta;
  fi
